DROP TABLE IF EXISTS types_of_products CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS people CASCADE;
DROP TABLE IF EXISTS person_product CASCADE;
DROP TABLE IF EXISTS role_in_server CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS cities CASCADE;

CREATE TABLE types_of_products(
	id_type_of_product INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(128) NOT NULL UNIQUE
);

CREATE TABLE products(
	id_product INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(256) NOT NULL,
	description TEXT,
	price NUMERIC NOT NULL,
	points INT,
	id_type_of_product INT REFERENCES types_of_products(id_type_of_product),
	accessible BOOLEAN NOT NULL
);

CREATE TABLE cities(
	id_city INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	name VARCHAR(128) NOT NULL
);

CREATE TABLE people(
	id_person INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	last_name VARCHAR(64) NOT NULL,
	first_name VARCHAR(64) NOT NULL,
	patronymic VARCHAR(64) NOT NULL,
	date_of_birth DATE,
	nickname VARCHAR(256) NOT NULL UNIQUE,
	points INT NOT NULL,
	path_avatar TEXT,
	phone_number VARCHAR(16),
	email VARCHAR(256),
	id_city INT REFERENCES cities(id_city),
	password TEXT
);

CREATE TABLE person_product(
	id_person_product INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	id_person INT REFERENCES people(id_person),
	id_product INT REFERENCES products(id_product),
	purchased BOOLEAN NOT NULL,
	raiting INT
);

CREATE TABLE images(
	id_image BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	id_product INT REFERENCES products(id_product),
	path TEXT NOT NULL
);

INSERT INTO types_of_products(name) VALUES
('Рюкзаки'),
('Чехлы'),
('Худи'),
('Шоперы'),
('Термо кружки');

INSERT INTO cities (name) VALUES
('Москва'),
('Санкт-Петербург'),
('Новосибирск'),
('Екатеринбург'),
('Казань'),
('Нижний Новгород'),
('Челябинск'),
('Самара'),
('Омск'),
('Ростов-на-Дону');

INSERT INTO products(name, description, price, points, id_type_of_product, accessible) VALUES
('Backpack 1', 'Description for Backpack 1', 50.00, 100, (SELECT id_type_of_product FROM types_of_products WHERE name='Рюкзаки'), TRUE),
('Backpack 2', 'Description for Backpack 2', 55.00, 110, (SELECT id_type_of_product FROM types_of_products WHERE name='Рюкзаки'), TRUE),
('Backpack 3', 'Description for Backpack 3', 60.00, 120, (SELECT id_type_of_product FROM types_of_products WHERE name='Рюкзаки'), TRUE),
('Backpack 4', 'Description for Backpack 4', 65.00, 130, (SELECT id_type_of_product FROM types_of_products WHERE name='Рюкзаки'), TRUE),

('Chehol 1', 'Description for Chehol 1', 10.00, 20, (SELECT id_type_of_product FROM types_of_products WHERE name='Чехлы'), TRUE),
('Chehol 2', 'Description for Chehol 2', 12.00, 24, (SELECT id_type_of_product FROM types_of_products WHERE name='Чехлы'), TRUE),
('Chehol 3', 'Description for Chehol 3', 14.00, 28, (SELECT id_type_of_product FROM types_of_products WHERE name='Чехлы'), TRUE),
('Chehol 4', 'Description for Chehol 4', 16.00, 32, (SELECT id_type_of_product FROM types_of_products WHERE name='Чехлы'), TRUE),
('Chehol 5', 'Description for Chehol 5', 18.00, 36, (SELECT id_type_of_product FROM types_of_products WHERE name='Чехлы'), TRUE),
('Chehol 6', 'Description for Chehol 6', 20.00, 40, (SELECT id_type_of_product FROM types_of_products WHERE name='Чехлы'), TRUE),

('Hoodie 1', 'Description for Hoodie 1', 30.00, 60, (SELECT id_type_of_product FROM types_of_products WHERE name='Худи'), TRUE),
('Hoodie 2', 'Description for Hoodie 2', 32.00, 64, (SELECT id_type_of_product FROM types_of_products WHERE name='Худи'), TRUE),
('Hoodie 3', 'Description for Hoodie 3', 34.00, 68, (SELECT id_type_of_product FROM types_of_products WHERE name='Худи'), TRUE),
('Hoodie 4', 'Description for Hoodie 4', 36.00, 72, (SELECT id_type_of_product FROM types_of_products WHERE name='Худи'), TRUE),

('Shopper 1', 'Description for Shopper 1', 5.00, 10, (SELECT id_type_of_product FROM types_of_products WHERE name='Шоперы'), TRUE),
('Shopper 2', 'Description for Shopper 2', 6.00, 12, (SELECT id_type_of_product FROM types_of_products WHERE name='Шоперы'), TRUE),
('Shopper 3', 'Description for Shopper 3', 7.00, 14, (SELECT id_type_of_product FROM types_of_products WHERE name='Шоперы'), TRUE),
('Shopper 4', 'Description for Shopper 4', 8.00, 16, (SELECT id_type_of_product FROM types_of_products WHERE name='Шоперы'), TRUE),

('Thermos Mug 1', 'Description for Thermos Mug 1', 15.00, 30, (SELECT id_type_of_product FROM types_of_products WHERE name='Термо кружки'), TRUE),
('Thermos Mug 2', 'Description for Thermos Mug 2', 17.00, 34, (SELECT id_type_of_product FROM types_of_products WHERE name='Термо кружки'), TRUE),
('Thermos Mug 3', 'Description for Thermos Mug 3', 19.00, 38, (SELECT id_type_of_product FROM types_of_products WHERE name='Термо кружки'), TRUE),
('Thermos Mug 4', 'Description for Thermos Mug 4', 21.00, 42, (SELECT id_type_of_product FROM types_of_products WHERE name='Термо кружки'), TRUE);

INSERT INTO images(id_product, path) VALUES
(1, '/backpaks/backpak1-1.jpg'),
(1, '/backpaks/backpak1-2.jpg'),
(2, '/backpaks/backpak2-1.jpg'),
(2, '/backpaks/backpak2-2.jpg'),
(3, '/backpaks/backpak3-1.jpg'),
(3, '/backpaks/backpak3-2.jpg'),
(4, '/backpaks/backpak4-1.jpg'),
(4, '/backpaks/backpak4-2.jpg'),
(5, '/chehols/chehol1-1.jpg'),
(6, '/chehols/chehol2-1.jpg'),
(7, '/chehols/chehol3-1.jpg'),
(8, '/chehols/chehol4-1.jpg'),
(9, '/chehols/chehol5-1.jpg'),
(10, '/chehols/chehol6-1.jpg'),
(11, '/hudi/hudi1-1.jpg'),
(11, '/hudi/hudi1-2.jpg'),
(12, '/hudi/hudi2-1.jpg'),
(12, '/hudi/hudi2-2.jpg'),
(13, '/hudi/hudi3-1.jpg'),
(13, '/hudi/hudi3-2.jpg'),
(14, '/hudi/hudi4-1.jpg'),
(14, '/hudi/hudi4-2.jpg'),
(15, '/shoppers/shopper1-1.jpg'),
(15, '/shoppers/shopper1-2.jpg'),
(16, '/shoppers/shopper2-1.jpg'),
(16, '/shoppers/shopper2-2.jpg'),
(17, '/shoppers/shopper3-1.jpg'),
(17, '/shoppers/shopper3-2.jpg'),
(18, '/shoppers/shopper4-1.jpg'),
(18, '/shoppers/shopper4-2.jpg'),
(19, '/termostakan/termostakan1-1.jpg'),
(20, '/termostakan/termostakan2-1.jpg'),
(21, '/termostakan/termostakan3-1.jpg'),
(22, '/termostakan/termostakan4-1.jpg');

INSERT INTO people (last_name, first_name, patronymic, nickname, points, phone_number, email, password, id_city, path_avatar)
VALUES
('Иванов', 'Иван', 'Иванович', 'ivan123', 100, '1234567890', 'ivan@example.com', '$2b$10$VoMmJOqlI5HXPLEMEI/35OgyrKCYJ8plpRfNzFKNg9uWR/Q6qcjVa', 1, '1.jpg'),
('Петров', 'Петр', 'Петрович', 'petr456', 150, '9876543210', 'petr@example.com', '$2b$10$jxAOp8ndHvcijJxIX8zfOOvh5yhQnxchTNHp6sOx4Xei2Ez5.NpxG', 2, '1.jpg'),
('Сидоров', 'Сидор', 'Сидорович', 'sidor789', 200, '5555555555', 'sidor@example.com', '$2b$10$YVhtzYbvP.BSt1k90n60A.ayettN2SPbBAf8BLTcUml/BQUzooF.e', 3, '2.jpg'),
('Кузнецов', 'Кузьма', 'Кузьмич', 'kuzma321', 50, '6666666666', 'kuzma@example.com', '$2b$10$drx.pPHb73FP4JawiWojWup3K34fDYv8.UOTVEkvqraIvn/Ri7t6m', 4, '2.jpg'),
('Федорова', 'Мария', 'Ивановна', 'masha654', 300, '7777777777', 'masha@example.com', '$2b$10$EFF1KhSTp9fXym8ztJ.G.eTASednUT7v0MXrKtqLeN.o30aJ0HEXC', 5, '3.jpg'),
('Морозов', 'Алексей', 'Алексеевич', 'alex987', 75, '8888888888', 'alex@example.com', '$2b$10$Um2FTWGRnRy7MUOEVv/9ruRNsLGpmAcuLgZYfgifQXQi4DQBcKyti', 6, '3.jpg'),
('Попова', 'Елена', 'Петровна', 'lena123', 120, '9999999999', 'lena@example.com', '$2b$10$69fzn03EtvjyzsOggs3boOcUJLVhK45WHRVDprdw9LI/K3e5zguOO', 7, '4.jpg'),
('Александров', 'Сергей', 'Александрович', 'sergey456', 90, '1010101010', 'sergey@example.com', '$2b$10$ZNLkuVVPGT8hF.8R5TNxreqgAgij7UiGpw3ryK4uOtFa/5hFVVN1a', 8, '4.jpg'),
('Яковлева', 'Анна', 'Владимировна', 'anna789', 180, '1212121212', 'anna@example.com', '$2b$10$oneYuLqEs/IZTL7IvJHMZeYQEJhlXeabb7Ya/ERRS.b37CbN6W4Oq', 9, '5.jpg'),
('Григорьев', 'Николай', 'Григорьевич', 'nik123', 250, '1313131313', 'nik@example.com', '$2b$10$kg1mHlo7c3JR6hwHFtpLi.FYpXF0hWkMjec9uPEy7VUsFNAEwxB1S', 10, '5.jpg');